#서버 포트
server : 
  port : 8000
  servlet:
    session:
      timeout: 10
      cookie:
        max-age: 10 # 
        http-only : true
        
spring:
  security:
    user:
      name: user
      password: qweasd        